### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by Guiorgy** [AIRLab-POLIMI/mushroom#100]
Can't install the package

```./python.exe -m pip install mushroom-rl```

**System information:**
- OS: Windows 10 (21H2, 19044.2006)
- Python version: 3.9 & 3.10
- Torch version: 1.12.1
- Mushroom version: 1.6.1, 1.7.2

**Logs**
```
Building wheel for mushroom_rl (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mushroom_rl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [344 lines of output]

...

LINK : fatal error LNK1104: cannot open file 'build\temp.win-amd64-cpython-310\Release\mushroom_rl/environments/mujoco_envs/humanoid_gait/_external_simulation\muscle_simulation_stepupdate.cp310-win_amd64.exp'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mushroom_rl
Failed to build mushroom_rl
ERROR: Could not build wheels for mushroom_rl, which is required to install pyproject.toml-based projects
```

**Comment by davide-tateo90** [comment]
This is a problem with your toolchain for Cython compilation. Unfortunately, we cannot support you with this issue.
We are discussing dropping the Cython dependency in the future, this may fix your installation issues.

Sorry for the late reply, but we are very busy and out of workforce.

**Comment by davide-tateo90** [comment]
Update: we decided to remove the dependency on Cython. You'll probably be able to install mushroom when 1.9.0 is released.
Reopen this issue if the problem persists after the new version's release.

**Comment by Guiorgy** [comment]
Just a heads-up,

```
$ python -c "import mushroom_rl; print(mushroom_rl.__version__)"
1.9.0
```

1.9.0 installs successfully. Thank you.

**Comment by davide-tateo90** [comment]
Happy to know that the problem is solved.
Unfortunately Cython is problematic.
For this reason, we removed every Cython dependency.
