### ISSUE TITLE
I save an agent with LinearParameter epsilon, when I load it, the epsilon is a Parameter

### ISSUE THREAD

**Issue by davidenitti** [AIRLab-POLIMI/mushroom#76]
**Describe the bug**
If I save an agent (even with full save) where I have a LinearParameter as epsilon for EpsGreedy, and I load the agent, the epsilon is a Parameter and not a LinearParameter, so I cannot continue with the same EpsGreedy policy.
My goal is to save an agent so I can resume the training.

**To Reproduce**
```
epsilon = LinearParameter(value=args.initial_exploration_rate,
                                  threshold_value=args.final_exploration_rate,
                                  n=args.final_exploration_frame)
pi = EpsGreedy(epsilon=epsilon)
[...]
agent = alg(mdp.info, pi, approximator,
                        approximator_params=approximator_params,
                        **algorithm_params)
agent.save('agent.msh', full_save=True)
[...]
agent = DQN.load('agent.msh')
#agent.policy._epsilon is a Parameter and not a LinearParameter
```

**Expected behavior**
I expect agent.policy._epsilon to be the same type when I reload an agent from disk

**System information (please complete the following information):**
- Python version Python3.8
- Mushroom version github version as of 10/11/2021

**Comment by davide-tateo90** [comment]
Unfortunately, we cannot debug and fix immediately as we are busy.
This bug seems to be problematic, thus we will try to fix it as soon as posible (beginning of the week).

Can you check if the issue is still there without full save? i.e. not saving the replay memory.

**Comment by davidenitti** [comment]
sorry it was my mistake, in the example atari_dqn.py the agent is saved the first time when test epsilon is set, so it was normal that when reloaded epsilon was a simple Parameter.
making a small change I can make sure to save always with the correct epsilon policy
so there is no bug.
thank you anyway
