### ISSUE TITLE
Mujoco 200 Dynamic Library Error If Configured with mushroom_rl

### ISSUE THREAD

**Issue by plaban** [AIRLab-POLIMI/mushroom#82]
**Describe the bug**

While configuring dm_control with mushroom_rl, I am finding difficulty in configuring mujoco200. Following is the error:

AttributeError: <HOME>/.mujoco/mujoco200/bin/libmujoco200.so: undefined symbol: mjr_label

Following are the environment variables set:

export MUJOCO_GL=osmesa
export MJLIB_PATH="<HOME>/.mujoco/mujoco200/bin/libmujoco200.so"
export MJKEY_PATH="<HOME>/.mujoco/mujoco200/mjkey.txt"
export MUJOCO_PY_MJPRO_PATH="<HOME>/.mujoco/mujoco200/"
export MUJOCO_PY_MJKEY_PATH="<HOME>/.mujoco/mujoco200/mjkey.txt"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:<HOME>/.mujoco/mujoco200/bin"

I am stuck for a long at this point. Kindly help

**To Reproduce**
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from mushroom_rl.algorithms.value import DQN

**Expected behavior**
No error

**System information (please complete the following information):**
- OS: [e.g. Ubuntu 20.04]
- Python version [Python3.7]
- Torch version [Pytorch 1.10]
- Mushroom version [1.70]

**Additional Context**
mujoco_py works perfectly fine as it can render environments from python code.

**Comment by davide-tateo90** [comment]
Have you tried the newest version of Mujoco?

you can download Mujoco 2.1.0 here:
https://mujoco.org/download

This version doesn't require a key and is easier to install. It should work almost out of the box.
