### ISSUE TITLE
REINFORCE with optional baseline

### ISSUE THREAD

**Issue by RylanSchaeffer** [AIRLab-POLIMI/mushroom#88]
REINFORCE, as implemented, always uses a baseline. I would like a flag that makes the baseline optional, specifically to explore the effect that a baseline has on REINFORCE.

**Comment by davide-tateo90** [comment]
We will not implement this feature, as REINFORCE without baseline is a useless algorithm. If the user wants to implement this approach, he can just modify the code of the algorithm or create his own class.
