### ISSUE TITLE
Incorrect Shape of Baseline in REINFORCE

### ISSUE THREAD

**Issue by RylanSchaeffer** [AIRLab-POLIMI/mushroom#89]
In `mushroom_rl.algorithms.policy_search.policy_gradient.reinforce`, the gradient is computed as:

```
    def _compute_gradient(self, J):
        baseline = np.mean(self.baseline_num, axis=0) / np.mean(self.baseline_den, axis=0)
        ...
```

However, the baseline numerator and denominator are calculated as:

```
        self.list_sum_d_log_pi.append(self.sum_d_log_pi)
        squared_sum_d_log_pi = np.square(self.sum_d_log_pi)
        self.baseline_num.append(squared_sum_d_log_pi * self.J_episode)
        self.baseline_den.append(squared_sum_d_log_pi)
```

We can see here that the `baseline_num` and `baseline_den` both have the same shape as `d_log_pi`, meaning `baseline` has the same shape. Surely the shape of the baseline should be a scalar?

**Comment by RylanSchaeffer** [comment]
Moreover, if you use only 1 episode to train, then the gradient will always be 0. This is because `grad_J_episode` is computed as:

`grad_J_episode = sum_d_log_pi * (J - baseline)`

and plugging in the baseline:

`grad_J_episode = sum_d_log_pi * (J - J  * sum_d_log_pi / sum_d_log_pi) = sum_d_log_pi * (J - J) = 0`

**Consequently, with this choice of baseline, an agent trained from single episodes will never learn.**

**Comment by davide-tateo90** [comment]
The baseline implementation is correct. This is the elementwise baseline, not the basic one.

Please, refer to the RL literature about this topic:
Marc Peter Deisenroth; Gerhard Neumann; Jan Peters, A Survey on Policy Search for Robotics, 2013.
https://ieeexplore.ieee.org/document/8186816

Also, the fact that the baseline is zero for a single episode trivially comes from the definition of baseline.

**Comment by RylanSchaeffer** [comment]
You misread what I wrote. The **baseline** isn't zero. The **gradient** is zero.

**Comment by RylanSchaeffer** [comment]
Consequently, if you train the agent only one episode at a time, then the gradient is always zero and the agent will never learn even if given infinite data and infinite time.

That cannot be correct.

**Comment by RylanSchaeffer** [comment]
Your citation is a book. Can you please be a little more precise?

**Comment by davide-tateo90** [comment]
The citation is a survey paper.

The fact that the gradient is zero depends exactly on the meaning of the baseline.

**Comment by RylanSchaeffer** [comment]
Ok so the Reinforce agent will never learn with 1 episode and this is
intended?

**Comment by davide-tateo90** [comment]
The normal use case for REINFORCE is to use multiple trajectories to estimate the gradient. 

We will put an assert to ensure that the user cannot run the algorithm with a single trajectory.

**Comment by RylanSchaeffer** [comment]
Alternatively, you could set the baseline to 0 if there's only one
trajectory?

**Comment by davide-tateo90** [comment]
this is also a behavior that we could consider. we will choose the option that minimizes the code.

REINFORCE without baseline and with a single trajectory is basically a useless algorithm, so it's not worth supporting this use case if it makes the code less clean.

**Comment by RylanSchaeffer** [comment]
Yep, totally agree! But that doesn't mean there aren't interesting research
questions to ask ;)
