### ISSUE TITLE
[solvers/dynamic_programming] Use np.linalg.solve instead of np.inv

### ISSUE THREAD

**Issue by Flo-Wo** [AIRLab-POLIMI/mushroom#95]
First of all, thank you for setting up such an amazing an easy to use library. While working with mushroom_rl on Finite MDPs, I stumbled along the solving process inside the ``policy_iteration`` function located in ``./solvers/dynamic_programming.py``.

[Line 76](https://github.com/MushroomRL/mushroom-rl/blob/ac3b0360dd9b9faaf0d67359c9cff063c45b7c89/mushroom_rl/solvers/dynamic_programming.py#L76) states
```python
value = np.linalg.inv(i - gamma * p_pi).dot(r_pi)
```

Here the computation can be easily substituted by just solving the corresponding linear system via
```python
value = np.linalg.solve(i - gamma * p_pi, r_pi)
```

This version should be way faster (as ``np.inv()`` internally solves the systems $Ax = e^{i}$ for $i=1,\ldots, n$) and mathematically more convenient (sometimes strange things happen when applying ``np.inv()`` to large dense matrices).

Regards,
Florian

**Comment by davide-tateo90** [comment]
Hi, thanks for reaching us.
Yes, we are well aware of the fact that using solve is a way more efficient way to compute the solution for these types of linear systems.
To be honest, the original implementation was done to be as close as possible to didactic examples of RL.
However, given that our library is growing, we might want to improve also the efficiency.

We thank you for your suggestion and we will definitely fix this in the next releases of Mushroom!

**Comment by davide-tateo90** [comment]
implemented in the latest commit
