### ISSUE TITLE
[requirements.txt] Missing requirement for OpenAI gym

### ISSUE THREAD

**Issue by Flo-Wo** [AIRLab-POLIMI/mushroom#97]
Problem:
While trying to run the example [montain_car_sarsa.py](https://github.com/MushroomRL/mushroom-rl/blob/dev/examples/mountain_car_sarsa.py) I got the error ``TypeError: 'NoneType' object is not callable``. By inspecting the ``./environment/__init__.py`` file, it was clear that [openai/gym](https://github.com/openai/gym) was missing.

Solution:
```shell
pip install gym
```
solved the issue, as well as addition the additional line ``gym`` in ``requirements.txt`` should solve this by default.

**Comment by davide-tateo90** [comment]
This is not a bug. The Gym class is an optional component of MushroomRL.

Please, take a look at the readme.
https://github.com/MushroomRL/mushroom-rl#installing-everything

for example, to install all the dependencies to run (most) Gym and Atari environments you can run:

pip install mushroom-rl[gym, atari, box2d]

**Comment by Flo-Wo** [comment]
You are perfectly right, thank you!

**Comment by davide-tateo90** [comment]
Updated README to make these points clear. Hopefully, it helps!

**Comment by Flo-Wo** [comment]
Thank you!
